### ISSUE TITLE
Errors while making concurrent requests using qumulo Python SDK

### ISSUE THREAD

**Issue by pallabpain** [Qumulo/qumulo-api-introduction#3]
I've been working with the `qumulo api` for the past few weeks and I've been observing frequent failures while running multiple operations concurrently. My tests mostly include performing multiple snapshot-based operations concurrently, like creating snapshots, creating exports, deleting snapshots, modifying exports, accessing snapshot diff, accessing snapshot info, etc.

A sample run usually includes around 100 directories on which snapshot-based operations are performed. However, I've noticed that oftentimes a lot of jobs just start failing with errors like `Request-sent` or `OSError: Bad file descriptor`.

I've made sure that the connection isn't reused for subsequent requests, `rc = RestClient(.., .., reuse_connection=False)` and I've added a backoff-retry logic on top of that where I refresh the connection before making the call again. However, I still see these errors sometimes.

How can I address this properly?

> P.S. I've also seen the issues frequently on a smaller set ~5-10 directories as well.

**Comment by pallabpain** [comment]
Here's a stack trace that I often get
```
Traceback (most recent call last):
  File "src/qumulo_nas/qumulo_nas.py", line 689, in create_diff
    for diff in diff_generator:
  File "src/qumulo_nas/qumulo_nas.py", line 312, in get_diff
    int(new_snap_id), int(old_snap_id), limit=chunk_size):
  File "/tmp/cloudpoint/libs/qumulo_nas/lib/qumulo/rest_client.py", line 53, in __next__
    return self.etag_strip_function(next(self.iterator))
  File "/tmp/cloudpoint/libs/qumulo_nas/lib/qumulo/lib/request.py", line 590, in __next__
    result = self.rest_request(self.uri)
  File "/tmp/cloudpoint/libs/qumulo_nas/lib/qumulo/rest/snapshot.py", line 235, in get_a_snapshot_tree_diff
    return request.rest_request(conninfo, credentials, 'GET', str(uri))
  File "/tmp/cloudpoint/libs/qumulo_nas/lib/qumulo/lib/request.py", line 562, in rest_request
    rest.send_request()
  File "/tmp/cloudpoint/libs/qumulo_nas/lib/qumulo/lib/request.py", line 456, in send_request
    self.conn.putrequest(self.method, self.uri)
  File "/usr/lib/python3.5/http/client.py", line 986, in putrequest
    raise CannotSendRequest(self.__state)
  http.client.CannotSendRequest: Request-sent
```

**Comment by TommyUnger** [comment]
Sorry for the delay here. What is the configuration of your Qumulo cluster (hardware, SW version, etc)? What is the configuration of your client machine (os version, python version)?

**Comment by TommyUnger** [comment]
Also, if possible, can you share your whole script here?

**Comment by pallabpain** [comment]
@TommyUnger Got in touch with some folks from Qumulo and found out that the `RestClient` is not thread-safe. So, I changed my implementation a bit and introduced a pool of `RestClient` objects and I haven't seen these issues since then.
