### ISSUE TITLE
Setup for REST API

### ISSUE THREAD

**Issue by n-mam** [Qumulo/qumulo-api-introduction#4]
I am trying to implement a kubernetes csi driver using REST API to interface with Qumulo NFS backend. I downloaded the OVA available on the website, merged all the split vmdk's into one and then converted the merged vmdk into a vhd file. Created a set of 4, 2-step differencing disk chain with the original vhd ("merged vmdk into a vhd file") as the parent of all 4 differencing disks. Created 4 VMs with 3072 MB RAM and started the first one. Accepted the EULA and allowed it to stabilize. Then sequentially started the remaining 3 VMs. As each VM came up online the first one's node list was updated accordingly. Finally I provided the cluster password and initiated the "Create Cluster" workflow. The operation however failed with the below error.

Could you please advise on what could be the issue here ? I have a i7 16GB MSI gaming laptop with a dedicated gfx card that can happily handle virtually any cv/ml workloads. But looks like this is not enough for testing the NFS REST API. Is there a less resource intensive way (like the aws single node cluster) that one could use to explore the REST interface ?

![image](https://user-images.githubusercontent.com/17683324/108549454-3246b680-7313-11eb-93e4-344d85714642.png)
![image](https://user-images.githubusercontent.com/17683324/108549418-26f38b00-7313-11eb-9450-ee184ce36aa0.png)

**Comment by TommyUnger** [comment]
Can you send an email to our care team with this question? They should be
able to help get you up and running with the OVA and Qumulo VM.

You can also reply to me directly via email I can
probably point you in the right direction.


*Tommy Unger*
Principal Data Scientist
____________________________________________________

*Qumulo* <https://qumulo.com/> - Store billions of files & petabytes of data

**Comment by n-mam** [comment]
Sure, I can do that. Thanks for the pointer. Closing this for now.
